version: '3.1'
services:
  db:
    container_name: db
    image: mysql:5.7.19
    environment:
      - MYSQL_DATABASE=databaseoiansiedade
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  app:
   build:
    dockerfile: ./Dockerfile
    context: .
   image: oiansiedade
   container_name: oiansiedade-api
   ports:
      - "8080:8080"
   environment:
     - MYSQL_HOST=db
   depends_on:
      - "db"
   links:
      - "db"
